function nav(active='inicio'){return `<header class="topbar"><div class="nav"><a class="brand brand-img-only" href="index.html"><img class="brand-img" src="assets/logo.png" alt="Link Corp"></a><nav class="menu"><a class="${active==='inicio'?'active':''}" href="index.html">Início</a><a class="${active==='produtos'?'active':''}" href="produtos.html">Produtos</a><a class="${active==='feedbacks'?'active':''}" href="feedbacks.html">Feedbacks</a><a class="${active==='login'?'active':''}" href="login.html">Login</a><button onclick="openCart()" class="cart-btn">🛒</button></nav></div></header>`}
function footer(){return `<footer class="footer"><div class="container footer-grid"><div><div class="brand brand-img-only"><img class="brand-img footer-logo-img" src="assets/logo.png" alt="Link Corp"></div><p>Os melhores painéis e produtos digitais. Atendimento manual via Pix e WhatsApp.</p><div class="secure"><b>🛡️ Segurança</b><span>Google Site Seguro</span><span>ReclameAQUI</span></div></div><div><h3>LINKS RÁPIDOS</h3><p><a href="produtos.html">Produtos</a></p><p><a href="feedbacks.html">Feedbacks</a></p><p><a href="carrinho.html">Carrinho</a></p></div><div><h3>SUPORTE</h3><p>💬 Suporte 24/7 via WhatsApp</p><p>✉️ ${cfg.SUPPORT_EMAIL}</p><p>🛡️ Pagamento Seguro</p></div></div><div class="container"><p>© 2026 Link Corp. Todos os direitos reservados.</p></div></footer><div class="online"><span id="onlineNum">150</span> ONLINE</div><button class="chat" onclick="window.open('https://wa.me/${cfg.WHATSAPP_NUMBER}','_blank')">💬</button><div id="toast" class="toast"></div><div id="cartModal" class="modal"><div class="modal-box"><button class="close" onclick="closeCart()">×</button><h2>Carrinho</h2><div id="cartItems"></div><a class="btn" href="carrinho.html">Finalizar Pedido</a></div></div>`}
function boot(active){document.body.classList.add('grid-bg');document.getElementById('nav').innerHTML=nav(active);document.getElementById('footer').innerHTML=footer();particles();setInterval(()=>{let n=145+Math.floor(Math.random()*20);let el=document.getElementById('onlineNum');if(el)el.textContent=n},2500)}
function toast(msg){let t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function particles(){for(let i=0;i<36;i++){let p=document.createElement('span');p.className='particle';p.style.left=Math.random()*100+'vw';p.style.animationDelay=Math.random()*9+'s';p.style.animationDuration=(7+Math.random()*8)+'s';document.body.appendChild(p)}}
async function fetchProducts(){if(!isConfigured())return demoProducts();const {data,error}=await supabase.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(error){console.error(error);return []}return data||[]}
function demoProducts(){return [{id:'demo1',category:'android',name:'Painel Link Android',description:'Painel otimizado para Android com planos flexíveis.',image_url:'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?q=80&w=900',old_price:99.9,price:35,badge:'Mais escolhido',plans:[{name:'15 Dias',days:'15 dias',old_price:49.99,price:35,discount:'-30%'},{name:'Mensal',days:'30 dias',old_price:99.99,price:65,discount:'-35%'},{name:'Trimestral',days:'90 dias',old_price:119.99,price:85,discount:'-29%'},{name:'Permanente',days:'Vitalício',old_price:179.99,price:120,discount:'-33%'}]},{id:'demo2',category:'ios',name:'Painel Link iOS',description:'Solução exclusiva para iOS.',image_url:'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?q=80&w=900',old_price:99.9,price:35,badge:'iPhone',plans:[{name:'15 Dias',days:'15 dias',old_price:49.99,price:35,discount:'-30%'},{name:'Mensal',days:'30 dias',old_price:99.99,price:65,discount:'-35%'},{name:'Permanente',days:'Vitalício',old_price:179.99,price:120,discount:'-33%'}]},{id:'demo3',category:'pc',name:'Internal Core Emulador',description:'Painel completo para emulador/PC.',image_url:'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=900',old_price:59.99,price:40,badge:'PC',plans:[{name:'15 Dias',days:'15 dias',old_price:59.99,price:40,discount:'-33%'},{name:'Mensal',days:'30 dias',old_price:89.99,price:65,discount:'-28%'},{name:'Trimestral',days:'90 dias',old_price:149.99,price:99.99,discount:'-33%'},{name:'Vitalício',days:'Vitalício',old_price:399.99,price:279.99,discount:'-30%'}]}]}
function productCard(p){return `<div class="product-card" data-cat="${p.category}"><img class="product-img" src="${p.image_url||''}" onerror="this.style.display='none'"><div class="product-body"><span class="badge">${p.badge||p.category}</span><h3 class="product-name">🛒 ${p.name}</h3><div class="prices"><del>${money(p.old_price)}</del> <span class="badge">↓ ${calcDisc(p.old_price,p.price)}</span></div><div class="price">${money(p.price)}</div><small>À vista no PIX</small><div class="buy-line"><button class="btn" onclick='buy(${JSON.stringify({id:p.id,name:p.name,price:p.price,plan:'Principal'}).replaceAll("'","&apos;")})'>Comprar</button></div></div></div>`}
function productWide(p){let plans=(p.plans&&p.plans.length?p.plans:[{name:'Comprar',days:'Acesso',old_price:p.old_price,price:p.price,discount:calcDisc(p.old_price,p.price)}]);return `<section class="product-wide" data-cat="${p.category}"><img class="wide-img" src="${p.image_url||''}"><div class="plans"><h2>${p.name}</h2><p style="color:#aeb5c2;font-size:18px">${p.description||''}</p>${plans.map(pl=>`<div class="plan"><div><div class="plan-title">${pl.name} <span class="badge">${pl.discount||calcDisc(pl.old_price,pl.price)}</span></div><span style="color:#7f8795">${pl.days||''}</span></div><div><del>${money(pl.old_price)}</del><div class="plan-price">${money(pl.price)}</div><small style="color:#0ee783">Economize ${money((pl.old_price||0)-(pl.price||0))}</small></div><button class="btn" onclick='buy(${JSON.stringify({id:p.id,name:p.name,price:pl.price,plan:pl.name}).replaceAll("'","&apos;")})'>🛒 Comprar</button></div>`).join('')}</div></section>`}
function calcDisc(oldp,price){oldp=Number(oldp||0);price=Number(price||0);return oldp>price?Math.round((1-price/oldp)*100)+'%':'0%'}
function buy(item){let cart=JSON.parse(localStorage.getItem('cart')||'[]');cart.push(item);localStorage.setItem('cart',JSON.stringify(cart));toast('Produto adicionado ao carrinho!')}
function openCart(){document.getElementById('cartModal').classList.add('show');renderCartMini()}function closeCart(){document.getElementById('cartModal').classList.remove('show')}
function renderCartMini(){let c=JSON.parse(localStorage.getItem('cart')||'[]');document.getElementById('cartItems').innerHTML=c.length?c.map((i,k)=>`<div class="plan"><b>${i.name}</b><span>${i.plan}</span><b>${money(i.price)}</b></div>`).join(''):'<p>Carrinho vazio.</p>'}
