// CONFIGURE AQUI DEPOIS DE CRIAR O SUPABASE
window.LINKCORP_CONFIG = {
  SUPABASE_URL: "COLE_AQUI_SUA_SUPABASE_URL",
  SUPABASE_ANON_KEY: "COLE_AQUI_SUA_SUPABASE_ANON_KEY",
  PIX_KEY: "COLE_AQUI_SUA_CHAVE_PIX",
  WHATSAPP_NUMBER: "5599999999999", // exemplo: 5577999999999
  SUPPORT_EMAIL: "suporte@linkcorp.com",
  ADMIN_EMAILS: ["seuemail@gmail.com"]
};
